<?php

########################################################################
# Extension Manager/Repository config file for ext: "cicslide"
#
# Auto generated by Extension Builder 2011-11-02
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CIC Slide',
	'description' => 'Generic slideshow/hero extension.',
	'category' => 'plugin',
	'author' => 'Michael McManus',
	'author_email' => 'michael@castironcoding.com',
	'author_company' => 'CIC',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'cicbase' => '0.1.1'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>